### ISSUE TITLE
When you die the stinkbomb does not disappear and the gas stays.

### ISSUE THREAD

**Issue by IDKANYMORE5** [ThisNoobPlays/Roblox-StinkBomb#2]
This is a big problem and should be fixed by making it so once you throw the item it's gone from your inventory instantly

**Comment by danielc129** [comment]
If I destroy the tool in the code it stops execution so I will look into some other method for the script to run and not be parented to backpack.

**Comment by danielc129** [comment]
I have made it so the tool is parented to workspace after you throw it
